const productsList = [
  {
    category: 'MTU',
    products: [
      {
				label: 'MTU 700',
				price: '',
        category: 'MTU',
        id: 24,
        img: 'mtu700.jpg',
        galery: ['mtu700.jpg', 'mtu700.jpg', 'mtu700.jpg', 'mtu700.jpg'],
        as: '/mtu-700',
        motorMark: 'MTU 8V4000 GS L32',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400',
        electricPower: 776,
        thermalPower: '886',
        electricEfficiency: '41,9',
        thermalEfficiency: '46,7',
        overallEfficiency: '88,6',
        fuelType: 'Природный газ ГОСТ 5542-87',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '175',
        noiseLevel: '80',
        serviceInterval: '1 500 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.',
        descriptionThree:
          'Области использования: буровые платформы и скважины, шахты, очистные сооружения, в качестве резервного, вспомогательного или основного источника электроэнергии на предприятиях, в строительстве, административных и медицинских учреждениях, аэропортах, гостиницах, узлах связи, системах жизнеобеспечения и т. п. в автономном режиме или совместно с централизованными системами электроснабжения и тепла.\nПо сравнению с микротурбинами у газопоршневых электростанций высокие показатели КПД, отсутствие влияние на КПД температуры окружающего воздуха, меньшее потребление газа по сравнении с микротурбинами, соответственно меньше выхлопа в окружающую среду. Стоимость газопоршневой электростанции обходится более чем в 2 раза дешевле чем у микротурбин.'
      },
      {
				label: 'MTU 800',
				price: '',
        category: 'MTU',
        id: 25,
        img: 'mtu800.jpg',
        galery: ['mtu800.jpg', 'mtu800.jpg', 'mtu800.jpg', 'mtu800.jpg'],
        as: '/mtu-800',
        motorMark: 'MTU 8V4000 GS L33',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400',
        electricPower: 854,
        thermalPower: '891',
        electricEfficiency: '42,8',
        thermalEfficiency: '44,8',
        overallEfficiency: '87,6',
        fuelType: 'Природный газ ГОСТ 5542-87',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '199',
        noiseLevel: '80',
        serviceInterval: '1 500 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.',
        descriptionThree:
          'Области использования: буровые платформы и скважины, шахты, очистные сооружения, в качестве резервного, вспомогательного или основного источника электроэнергии на предприятиях, в строительстве, административных и медицинских учреждениях, аэропортах, гостиницах, узлах связи, системах жизнеобеспечения и т. п. в автономном режиме или совместно с централизованными системами электроснабжения и тепла.\nПо сравнению с микротурбинами у газопоршневых электростанций высокие показатели КПД, отсутствие влияние на КПД температуры окружающего воздуха, меньшее потребление газа по сравнении с микротурбинами, соответственно меньше выхлопа в окружающую среду. Стоимость газопоршневой электростанции обходится более чем в 2 раза дешевле чем у микротурбин.'
      },
      {
				label: 'MTU 1000',
				price: '',
        category: 'MTU',
        id: 26,
        img: 'mtu1000.jpg',
        galery: ['mtu1000.jpg', 'mtu1000.jpg', 'mtu1000.jpg', 'mtu1000.jpg'],
        as: '/mtu-1000',
        motorMark: 'MTU 8V4000 GS L64',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400',
        electricPower: 1013,
        thermalPower: '969',
        electricEfficiency: '43,4',
        thermalEfficiency: '42,6',
        overallEfficiency: '86',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '273',
        noiseLevel: '80',
        serviceInterval: '1 500 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 1100',
				price: '',
        category: 'MTU',
        id: 27,
        img: 'mtu1100.jpg',
        galery: ['mtu1100.jpg', 'mtu1100.jpg', 'mtu1100.jpg', 'mtu1100.jpg'],
        as: '/mtu-1100',
        motorMark: 'MTU 12V4000 GS L33',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 1169,
        thermalPower: '1228',
        electricEfficiency: '42,8',
        thermalEfficiency: '45,0',
        overallEfficiency: '87,8',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '273',
        noiseLevel: '80',
        serviceInterval: '800 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 1200',
				price: '',
        category: 'MTU',
        id: 28,
        img: 'mtu1200.jpg',
        galery: ['mtu1200.jpg', 'mtu1200.jpg', 'mtu1200.jpg', 'mtu1200.jpg'],
        as: '/mtu-1200',
        motorMark: 'MTU 12V4000 GS L33',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 1286,
        thermalPower: '1323',
        electricEfficiency: '43,2',
        thermalEfficiency: '44,5',
        overallEfficiency: '87,7',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '298',
        noiseLevel: '80',
        serviceInterval: '2000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 1500',
				price: '',
        category: 'MTU',
        id: 29,
        img: 'mtu1500.jpg',
        galery: ['mtu1500.jpg', 'mtu1500.jpg', 'mtu1500.jpg', 'mtu1500.jpg'],
        as: '/mtu-1500',
        motorMark: 'MTU 12V4000 GS L64',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 1521,
        thermalPower: '1403',
        electricEfficiency: '44,3',
        thermalEfficiency: '40,8',
        overallEfficiency: '85,1',
        fuelType: 'Природный газ ГОСТ 5542-87',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '344',
        noiseLevel: '80',
        serviceInterval: '2000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 1600',
				price: '',
        category: 'MTU',
        id: 30,
        img: 'mtu1600.jpg',
        galery: ['mtu1600.jpg', 'mtu1600.jpg', 'mtu1600.jpg', 'mtu1600.jpg'],
        as: '/mtu-1600',
        motorMark: 'MTU 16V4000 GS L33',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 1560,
        thermalPower: '1662',
        electricEfficiency: '42,8',
        thermalEfficiency: '45,6',
        overallEfficiency: '88,4',
        fuelType: 'Природный газ ГОСТ 5542-87',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '365',
        noiseLevel: '80',
        serviceInterval: '2000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 1700',
				price: '',
        category: 'MTU',
        id: 31,
        img: 'mtu1700.jpg',
        galery: ['mtu1700.jpg', 'mtu1700.jpg', 'mtu1700.jpg', 'mtu1700.jpg'],
        as: '/mtu-1700',
        motorMark: 'MTU 16V4000 GS L33',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 1718,
        thermalPower: '1795',
        electricEfficiency: '43',
        thermalEfficiency: '45',
        overallEfficiency: '88',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '399',
        noiseLevel: '80',
        serviceInterval: '2000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 2000',
				price: '',
        category: 'MTU',
        id: 32,
        img: 'mtu2000.jpg',
        galery: ['mtu2000.jpg', 'mtu2000.jpg', 'mtu2000.jpg', 'mtu2000.jpg'],
        as: '/mtu-2000',
        motorMark: 'MTU 16V4000 GS L64',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 2028,
        thermalPower: '1901',
        electricEfficiency: '44,3',
        thermalEfficiency: '41,6',
        overallEfficiency: '85,9',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '457',
        noiseLevel: '80',
        serviceInterval: '2000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MTU 2145',
				price: '',
        category: 'MTU',
        id: 33,
        img: 'mtu2000.jpg',
        galery: ['mtu2000.jpg', 'mtu2000.jpg', 'mtu2000.jpg', 'mtu2000.jpg'],
        as: '/mtu-2000',
        motorMark: 'MTU 20V4000 GS L33',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6300, 10500',
        electricPower: 2145,
        thermalPower: '2239',
        electricEfficiency: '43',
        thermalEfficiency: '44,9',
        overallEfficiency: '87,9',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '',
        nominalGazConsumption: '499',
        noiseLevel: '80',
        serviceInterval: '2000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      }
    ]
  },
  {
    category: 'MAN',
    products: [
      {
				label: 'MAN 200',
				price: '9 000 000',
        category: 'MAN',
        id: 0,
        img: 'MAN200.jpg',
        galery: ['MAN200.jpg', 'MAN200.jpg', 'MAN200.jpg', 'MAN200.jpg'],
        as: '/man-200',
        motorMark: 'MAN E 3262 E 302',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1',
        voltage: '400',
        electricPower: 200,
        thermalPower: '316',
        electricEfficiency: '36,7',
        thermalEfficiency: '56,3',
        overallEfficiency: '93',
        fuelType:
          'Природный газ ГОСТ 5542-87, попутный нефтяной газ, пропан-бутановая смесь.',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '59.6',
        noiseLevel: '80',
        serviceInterval: '1 500 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MAN 250',
				price: '9 500 000',
        category: 'MAN',
        id: 1,
        img: 'MAN250.jpg',
        galery: ['MAN250.jpg', 'MAN250.jpg', 'MAN250.jpg', 'MAN250.jpg'],
        as: '/man-250',
        motorMark: 'MAN E 3262 E 302',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1',
        voltage: '400',
        electricPower: 250,
        thermalPower: '380',
        electricEfficiency: '38',
        thermalEfficiency: '54,8',
        overallEfficiency: '92,8',
        fuelType:
          'Природный газ ГОСТ 5542-87, попутный нефтяной газ, пропан-бутановая смесь.',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '67',
        noiseLevel: '80',
        serviceInterval: '1 500 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MAN 300',
				price: '11 600 000',
        category: 'MAN',
        id: 2,
        img: 'MAN300.jpg',
        galery: ['MAN300.jpg', 'MAN300.jpg', 'MAN300.jpg', 'MAN300.jpg'],
        as: '/man-300',
        motorMark: 'MAN E 3268 LE 242',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1,7',
        voltage: '400',
        electricPower: 300,
        thermalPower: '350',
        electricEfficiency: '41,7',
        thermalEfficiency: '47,5',
        overallEfficiency: '89,2',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '78',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MAN 350',
				price: '12 000 000',
        category: 'MAN',
        id: 3,
        img: 'MAN350.jpg',
        galery: ['MAN350.jpg', 'MAN350.jpg', 'MAN350.jpg', 'MAN350.jpg'],
        as: '/man-350',
        motorMark: 'MAN E 3268 LE 202',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1,69',
        voltage: '400',
        electricPower: 350,
        thermalPower: '445',
        electricEfficiency: '40,2',
        thermalEfficiency: '50,1',
        overallEfficiency: '90,3',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '91',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MAN 430',
				price: '',
        category: 'MAN',
        id: 4,
        img: 'MAN500.jpg',
        galery: ['MAN500.jpg', 'MAN500.jpg', 'MAN500.jpg', 'MAN500.jpg'],
        as: '/man-430',
        motorMark: 'MAN E3262 LE232',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1,6',
        voltage: '400',
        electricPower: 430,
        thermalPower: '505',
        electricEfficiency: '39,7',
        thermalEfficiency: '50,6',
        overallEfficiency: '90,3',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '107',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'MAN 530',
				price: '',
        category: 'MAN',
        id: 5,
        img: 'MAN500.jpg',
        galery: ['MAN500.jpg', 'MAN500.jpg', 'MAN500.jpg', 'MAN500.jpg'],
        as: '/man-500',
        motorMark: 'MAN E3262 LE 202',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1,63',
        voltage: '400, 6 300, 10 500',
        electricPower: 500,
        thermalPower: '652',
        electricEfficiency: '40,6',
        thermalEfficiency: '49,8',
        overallEfficiency: '90,4',
        fuelType:
          'Природный газ ГОСТ 5542-87, попутный нефтяной газ, пропан-бутановая смесь.',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '135',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      }
    ]
  },
  {
    category: 'LIEBHERR',
    products: [
      {
				label: 'LIEBHERR 230',
				price: '',
        category: 'LIEBHERR',
        id: 10,
        img: 'liebherr-230.jpg',
        galery: [
          'liebherr-230.jpg',
          'liebherr-230.jpg',
          'liebherr-230.jpg',
          'liebherr-230.jpg'
        ],
        as: '/LIEBHERR-230',
        motorMark: 'Liebherr G946',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1,74',
        voltage: '400',
        electricPower: 230,
        thermalPower: '262',
        electricEfficiency: '41,5',
        thermalEfficiency: '44,2',
        overallEfficiency: '85,7',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '59.2',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'LIEBHERR 300',
				price: '',
        category: 'LIEBHERR',
        id: 11,
        img: 'liebherr-230.jpg',
        galery: [
          'liebherr-230.jpg',
          'liebherr-230.jpg',
          'liebherr-230.jpg',
          'liebherr-230.jpg'
        ],
        as: '/LIEBHERR-300',
        motorMark: 'Liebherr G9508',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1,7',
        voltage: '400',
        electricPower: 300,
        thermalPower: '340',
        electricEfficiency: '40',
        thermalEfficiency: '42',
        overallEfficiency: '82',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '78',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'LIEBHERR 500',
				price: '',
        category: 'LIEBHERR',
        id: 12,
        img: 'liebherr-230.jpg',
        galery: [
          'liebherr-230.jpg',
          'liebherr-230.jpg',
          'liebherr-230.jpg',
          'liebherr-230.jpg'
        ],
        as: '/LIEBHERR-500',
        motorMark: 'Liebherr G9512',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1.7',
        voltage: '400, 6 300, 10 500',
        electricPower: 500,
        thermalPower: '652',
        electricEfficiency: '40,6',
        thermalEfficiency: '49,8',
        overallEfficiency: '90,4',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '135',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'LIEBHERR 1000',
				price: '',
        category: 'LIEBHERR',
        id: 13,
        img: 'liebherr-1000.jpg',
        galery: [
          'liebherr-1000-1.jpg',
          'liebherr-1000-2.jpg',
          'liebherr-1000-1.jpg',
          'liebherr-1000-2.jpg'
        ],
        as: '/LIEBHERR-1000',
        motorMark: 'Liebherr G9620',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1.7',
        voltage: '400, 6 300, 10 500',
        electricPower: 1000,
        thermalPower: '1 100',
        electricEfficiency: '44',
        thermalEfficiency: '43,5',
        overallEfficiency: '87,5',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '20-200',
        nominalGazConsumption: '265',
        noiseLevel: '80',
        serviceInterval: '1 000 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      }
    ]
  },
  {
    category: 'YAMZ',
    products: [
      {
				label: 'ЯМЗ 100',
				price: '3 500 000',
        category: 'YAMZ',
        id: 20,
        img: 'YAMZ100.jpg',
        galery: [
          'YAMZ100.jpg',
          'yamz-100-1.jpg',
          'YAMZ100.jpg',
          'yamz-100-1.jpg'
        ],
        as: '/yamz-100',
        motorMark: 'ЯМЗ 536 CNG',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1.6',
        voltage: '400',
        electricPower: 100,
        thermalPower: '100',
        electricEfficiency: '44',
        thermalEfficiency: '43,5',
        overallEfficiency: '87,5',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '31.9',
        noiseLevel: '80',
        serviceInterval: '800 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'ЯМЗ 140',
				price: '4 000 000',
        category: 'YAMZ',
        id: 21,
        img: 'YAMZ140.jpg',
        galery: ['YAMZ140.jpg', 'YAMZ140.jpg', 'YAMZ140.jpg', 'YAMZ140.jpg'],
        as: '/yamz-140',
        motorMark: 'ЯМЗ 536 CNG',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1.6',
        voltage: '400',
        electricPower: 140,
        thermalPower: '190',
        electricEfficiency: '44',
        thermalEfficiency: '43,5',
        overallEfficiency: '87,5',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '40',
        noiseLevel: '80',
        serviceInterval: '800 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'ЯМЗ 200',
				price: '4 500 000',
        category: 'YAMZ',
        id: 22,
        img: 'YAMZ200.jpg',
        galery: ['YAMZ200.jpg', 'YAMZ200.jpg', 'YAMZ200.jpg', 'YAMZ200.jpg'],
        as: '/yamz-200',
        motorMark: 'ТМЗ 8425',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1.6',
        voltage: '400',
        electricPower: 200,
        thermalPower: '280',
        electricEfficiency: '29',
        thermalEfficiency: '40,6',
        overallEfficiency: '69,6',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '66',
        noiseLevel: '80',
        serviceInterval: '800 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'ЯМЗ 300',
				price: '',
        category: 'YAMZ',
        id: 23,
        img: 'YAMZ300.jpg',
        galery: ['YAMZ300.jpg', 'YAMZ300.jpg', 'YAMZ300.jpg', 'YAMZ300.jpg'],
        as: '/yamz-300',
        motorMark: 'ЯМЗ 850.10',
        gasMixer: 'Motortech VariFuel2',
        controlBlock: 'Motortech VariStep3',
        ignitionSystem: 'Motortech MIC4',
        throttleValve: 'Motortech ITB',
        excessAirRatio: '1.6',
        voltage: '400',
        electricPower: 280,
        thermalPower: '450',
        electricEfficiency: '30',
        thermalEfficiency: '47',
        overallEfficiency: '77',
        fuelType: 'Природный газ',
        methaneNumber: 'Более 80',
        gasPressure: '0,05',
        nominalGazConsumption: '90',
        noiseLevel: '80',
        serviceInterval: '800 моточасов',
        totalPowerPlant: 'Не менее 15 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: 'Karl Dungs',
        freezGroup: 'Alfa Laval',
        nasos: 'Grundfos',
        powerSup: 'ABB',
        controlSystem: 'Motortech AIO',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      }
    ]
  },
  {
    category: 'JENBACHER',
    products: [
      {
				label: 'JENBACHER 630',
				price: '',
        category: 'JENBACHER',
        id: 40,
        img: 'jenbacher-630.jpg',
        galery: [
          'jenbacher630.jpg',
          'jenbacher630.jpg',
          'jenbacher630.jpg',
          'jenbacher630.jpg'
        ],
        as: '/jenbacher-630',
        motorMark: 'GE JENBACHER J312 GS',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400',
        electricPower: 635,
        thermalPower: '739',
        electricEfficiency: '40.8',
        thermalEfficiency: '47.4',
        overallEfficiency: '88.2',
        fuelType: 'Природный газ',
        methaneNumber: '80',
        gasPressure: '2-4',
        nominalGazConsumption: '164',

        oilconsumption: '0.2',
        airconsumption: '3279',

        noiseLevel: '123',
        serviceInterval: '',
        totalPowerPlant: 'Не менее 20 лет',
        generator: 'Stamford',
        gazLline: '',
        freezGroup: 'Alfa Laval',
        nasos: '',
        powerSup: 'ABB',
        controlSystem: 'DIA.NE',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'JENBACHER 1000',
				price: '',
        category: 'JENBACHER',
        id: 41,
        img: 'jenbacher-1000.jpg',
        galery: [
          'jenbacher-1000.jpg',
          'jenbacher-1000.jpg',
          'jenbacher-1000.jpg',
          'jenbacher-1000.jpg'
        ],
        as: '/jenbacher-1000',
        motorMark: 'GE JENBACHER J320 GS',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6 300, 10 500',
        electricPower: 1067,
        thermalPower: '1241',
        electricEfficiency: '40.9',
        thermalEfficiency: '47.6',
        overallEfficiency: '88.5',
        fuelType: 'Природный газ',
        methaneNumber: '80',
        gasPressure: '2-4',
        nominalGazConsumption: '274',

        oilconsumption: '0.33',
        airconsumption: '5 485',

        noiseLevel: '130',
        serviceInterval: '',
        totalPowerPlant: 'Не менее 20 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: '',
        freezGroup: 'Alfa Laval',
        nasos: '',
        powerSup: 'ABB',
        controlSystem: 'DIA.NE',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'JENBACHER 1500',
				price: '',
        category: 'JENBACHER',
        id: 42,
        img: 'jenbacher-1500.jpg',
        galery: [
          'jenbacher-1500.jpg',
          'jenbacher-1500.jpg',
          'jenbacher-1500.jpg',
          'jenbacher-1500.jpg'
        ],
        as: '/jenbacher-1500',
        motorMark: 'GE JENBACHER J420 GS',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6 300, 10 500',
        electricPower: 1497,
        thermalPower: '1546',
        electricEfficiency: '43.3',
        thermalEfficiency: '44.7',
        overallEfficiency: '88.0',
        fuelType: 'Природный газ',
        methaneNumber: '80',
        gasPressure: '0,12-0,2',
        nominalGazConsumption: '364',

        oilconsumption: '0.31',
        airconsumption: '7 831',

        noiseLevel: '123',
        serviceInterval: '',
        totalPowerPlant: 'Не менее 20 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: '',
        freezGroup: 'Alfa Laval',
        nasos: '',
        powerSup: 'ABB',
        controlSystem: 'DIA.NE',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'JENBACHER 2000',
				price: '',
        category: 'JENBACHER',
        id: 43,
        img: 'jenbacher-2000.jpg',
        galery: [
          'jenbacher-2000.jpg',
          'jenbacher-2000.jpg',
          'jenbacher-2000.jpg',
          'jenbacher-2000.jpg'
        ],
        as: '/jenbacher-2000',
        motorMark: 'GE JENBACHER J612 GS',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6 300, 10 500',
        electricPower: 2004,
        thermalPower: '1 883',
        electricEfficiency: '45.5',
        thermalEfficiency: '42.8',
        overallEfficiency: '88.3',
        fuelType: 'Природный газ',
        methaneNumber: '80',
        gasPressure: '4-8',
        nominalGazConsumption: '464',

        oilconsumption: '0.41',
        airconsumption: '10 906',

        noiseLevel: '80',
        serviceInterval: '',
        totalPowerPlant: 'Не менее 20 лет',
        generator: 'Leroy Somer, Stamford',
        gazLline: '',
        freezGroup: 'Alfa Laval',
        nasos: '',
        powerSup: 'ABB',
        controlSystem: 'DIA.NE',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      },
      {
				label: 'JENBACHER 4000',
				price: '',
        category: 'JENBACHER',
        id: 44,
        img: 'jenbacher-4000.jpg',
        galery: [
          'jenbacher-4000.jpg',
          'jenbacher-4000.jpg',
          'jenbacher-4000.jpg',
          'jenbacher-4000.jpg'
        ],
        as: '/jenbacher-4000',
        motorMark: 'GE JENBACHER J624 GS',
        gasMixer: '',
        controlBlock: '',
        ignitionSystem: '',
        throttleValve: '',
        excessAirRatio: '',
        voltage: '400, 6 300, 10 500',
        electricPower: 4404,
        thermalPower: '4 050 ',
        electricEfficiency: '46.6',
        thermalEfficiency: '42.9',
        overallEfficiency: '89.5',
        fuelType: 'Природный газ',
        methaneNumber: '80',
        gasPressure: '6-8',
        nominalGazConsumption: '994',

        oilconsumption: '0.9',
        airconsumption: '994',

        noiseLevel: '131',
        serviceInterval: '',
        totalPowerPlant: 'Не менее 20 лет',
        generator: 'TDPS',
        gazLline: '',
        freezGroup: 'Alfa Laval',
        nasos: '',
        powerSup: 'ABB',
        controlSystem: 'DIA.NE',
        descriptionOne:
          'Газопоршневая электростанция предназначена для комбинированной автономной выработки электрической и тепловой энергии в островном режиме работы либо в режиме синхронизации с электрическими сетями.',
        descriptionTwo:
          'Электростанция предназначена для круглосуточной непрерывной эксплуатации на номинальной нагрузке. В качестве привода генератора применяется газопоршневой двигатель с внешним смесеобразованием и искровым зажиганием горючей смеси в камере сгорания, использующий в качестве топлива газ и работающий по циклу Отто. В качестве топлива используются различные виды газа: природный, газы с низкой теплотворной способностью, невысоким содержанием метана и низкой степенью детонации или газы с высокой теплотворной способностью - факельный, пропан, бутан.'
      }
    ]
  }
].map(link => {
  link.key = `nav-link-${link.id}-${link.electricPower}`;
  return link;
});

export default productsList;
